// <auto-generated />
using EasyFinance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EasyFinance.Migrations.LoanProduct
{
    [DbContext(typeof(LoanProductContext))]
    [Migration("20200824140146_MyThirdMigration")]
    partial class MyThirdMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EasyFinance.Models.Banks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedAt");

                    b.Property<string>("LogoImage");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("EasyFinance.Models.LoanProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AgeMax")
                        .IsRequired();

                    b.Property<string>("AgeMin")
                        .IsRequired();

                    b.Property<int>("BankId");

                    b.Property<string>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FinancialMax")
                        .IsRequired();

                    b.Property<string>("FinancialMin")
                        .IsRequired();

                    b.Property<string>("InterestRate")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Summary");

                    b.Property<string>("TenureMax")
                        .IsRequired();

                    b.Property<string>("TenureMin")
                        .IsRequired();

                    b.Property<int>("TypeId");

                    b.Property<string>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("TypeId");

                    b.ToTable("LoanProduct");
                });

            modelBuilder.Entity("EasyFinance.Models.LoanTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.Property<string>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("LoanTypes");
                });

            modelBuilder.Entity("EasyFinance.Models.LoanProduct", b =>
                {
                    b.HasOne("EasyFinance.Models.Banks", "Banks")
                        .WithMany("LoanProducts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EasyFinance.Models.LoanTypes", "LoanTypes")
                        .WithMany("LoanProducts")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
